# Generated by Django 4.2 on 2023-06-08 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_messages_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timing',
            field=models.TimeField(default=datetime.datetime(2023, 6, 8, 15, 51, 57, 617863)),
        ),
    ]
